<?php

namespace gestorBundle\Repository;

/**
 * alumnosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class alumnosRepository extends \Doctrine\ORM\EntityRepository
{
}
