<?php

namespace gestorBundle\Repository;

/**
 * empresasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class empresasRepository extends \Doctrine\ORM\EntityRepository
{
}
