<?php

namespace gestorBundle\Repository;

/**
 * profeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profeRepository extends \Doctrine\ORM\EntityRepository
{
}
