gestor_homepage:
    path:     /
    defaults: { _controller: gestorBundle:Default:index }

all_empresas:
    path:     /empresas/all
    defaults: { _controller: gestorBundle:empresas:all }

nuevo_empresas:
    path:     /empresas/nuevo
    defaults: { _controller: gestorBundle:empresas:nuevo }

all_profe:
    path:     /profe/all
    defaults: { _controller: gestorBundle:profe:all }

nuevo_profe:
    path:     /profe/nuevo
    defaults: { _controller: gestorBundle:profe:nuevo }

all_alumnos:
    path:     /alumnos/all
    defaults: { _controller: gestorBundle:alumnos:all }

api:
    path:     /API
    defaults: { _controller: gestorBundle:API:empresas }
    methods: [GET]
