gestor_homepage:
    path:     /
    defaults: { _controller: gestorBundle:Default:index }

all_empresas:
    path:     /empresas/all
    defaults: { _controller: gestorBundle:empresas:all }

nuevo_empresas:
    path:     /empresas/nuevo
    defaults: { _controller: gestorBundle:empresas:nuevo }
